### ISSUE TITLE
2-Product

### ISSUE THREAD

**Issue by janis-rullis** [janis-rullis/pr1#9]
## Tasks

- [x] DB table.
- [x] Create.
- [x] List.
- [x] Show.
- [x] Tests.

## Involved data

- User. #8
- Title.
- SKU Unique.
- Cost.
- Product type.

## Useful

- https://github.com/janis-rullis/pr1/wiki

## Due date

- February 28, 2020

**Comment by janis-rullis** [comment]
# #18 Evaluate @lauris-printify code against requirements in the MVP

## DB table

### Possible table improvements

- `sku` - add a `UNIQUE INDEX`.
- integers - add `UNSIGNED`.
- `type` - change to ENUM, more readable in DB level and faster, especially if indexed.

## Create

* `src/Controller/ProductController.php::createProduct()`.
* `* @Route("/users/{id_user}/products", name="createProduct", methods={"POST"})`.
* `src/Product/ProductCreator.php`
* `src/Entity/Product.php`

## List

* `@Route("/users/{id_user}/products/{id}", name="getProduct", methods={"GET"})`
* `src/Controller/ProductController.php::getProducts()`


## Show

* `@Route("/users/{id_user}/products/{id}", name="getProduct", methods={"GET"})`
* `src/Controller/ProductController.php::getProductById()`

## Tests

* `src/Product/ProductValidator.php`

### Create

* ProductCreatorTest.php
* ValidateProductTest.php

* [x] Type check on insert `ProductTypeValidator`.
* [x] Unique SKU - `SkuValidator`.
* [x] Valid price, though maybe should limit to not be above 100$.
* [x] Title allows - alphanumerics.


### Tests ownership

* `GetProductTest.php`
* `GetProductsTest`.
